import type { Metadata } from "next";
import "./styles/globals.css";
import Navbar from "@/app/components/Navbar/Navbar";
import styles from "./Layout.module.css";
import {Montserrat} from "next/font/google";
import Footer from "@/app/components/Footer/Footer";

const MontserratSans = Montserrat({
  variable: "--font-sans",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Sneakers Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${MontserratSans.variable}`}
      >
        <Navbar />

        <div className={styles.mainContainer}>
          {children}
        </div>

        <Footer
          phone="+7 (999) 999-99-99"
          email="test@test.com"
        />
      </body>
    </html>
  );
}
