import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/app/components/Navbar/Navbar";
import styles from "./Layout.module.css";
import {Montserrat} from "next/font/google";

const MontserratSans = Montserrat({
  variable: "--font-sans",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Sneakers Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${MontserratSans.variable}`}
      >
        <div className={styles.mainContainer}>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
