import type { Metadata, Viewport } from "next";
import "./styles/globals.css";
import Navbar from "@/src/widgets/layout/Navbar/Navbar";
import styles from "./Layout.module.css";
import { Montserrat } from "next/font/google";
import Footer from "@/src/widgets/layout/Footer/Footer";
import AuthModalProvider from "../widgets/auth-modal/ui/AuthModalProvider";
import { SessionProvider } from "next-auth/react";

const MontserratSans = Montserrat({
  variable: "--font-sans",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Sneaker Shop",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${MontserratSans.variable}`}
      >
        <SessionProvider>
          <div className={styles.page}>
            <Navbar />

            <main className={styles.main}>
              <div className={styles.container}>
                {children}
              </div>
            </main>

            <AuthModalProvider />

            <Footer
              phone="+7 (999) 999-99-99"
              email="test@test.com"
            />
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
