export const sneakers = [
    {
        id: '1',
        name: 'Air Max Pro',
        brand: 'Nike',
        price: 129.99,
        image: '/images/sneaker-1.jpg',
        description:
            'Premium athletic sneaker with advanced cushioning technology for all-day comfort.',
        sizes: [6, 7, 8, 9, 10, 11, 12, 13],
        colors: ['Black', 'White', 'Blue', 'Red'],
        rating: 4.8,
        inStock: true,
    },
    {
        id: '2',
        name: 'Ultraboost Pulse',
        brand: 'Adidas',
        price: 139.99,
        image: '/images/sneaker-2.jpg',
        description:
            'Responsive running shoe with breathable knit upper and energy-returning midsole.',
        sizes: [6, 7, 8, 9, 10, 11, 12],
        colors: ['Gray', 'White', 'Lime'],
        rating: 4.7,
        inStock: true,
    },
    {
        id: '3',
        name: 'Clyde Classic',
        brand: 'Puma',
        price: 109.5,
        image: '/images/sneaker-3.jpg',
        description:
            'Retro-inspired low-top with soft suede upper and cushioned footbed for daily wear.',
        sizes: [7, 8, 9, 10, 11, 12],
        colors: ['Navy', 'Cream', 'Burgundy'],
        rating: 4.5,
        inStock: true,
    },
    {
        id: '4',
        name: 'Gel-Kayano Edge',
        brand: 'ASICS',
        price: 149.0,
        image: '/images/sneaker-1.jpg',
        description:
            'Stability trainer featuring gel cushioning, engineered mesh, and secure heel support.',
        sizes: [6, 7, 8, 9, 10, 11, 12, 13],
        colors: ['Black', 'Teal', 'Orange'],
        rating: 4.9,
        inStock: true,
    },
    {
        id: '5',
        name: 'Fresh Foam City',
        brand: 'New Balance',
        price: 124.99,
        image: '/images/sneaker-2.jpg',
        description:
            'Lightweight lifestyle runner with plush Fresh Foam midsole and street-ready style.',
        sizes: [6, 7, 8, 9, 10, 11, 12],
        colors: ['White', 'Mint', 'Stone'],
        rating: 4.6,
        inStock: true,
    },
    {
        id: '6',
        name: 'Zoom Street Fly',
        brand: 'Nike',
        price: 119.99,
        image: '/images/sneaker-3.jpg',
        description:
            'Sleek silhouette built for quick city moves with responsive Zoom Air cushioning.',
        sizes: [6, 7, 8, 9, 10, 11],
        colors: ['Black', 'Volt', 'Silver'],
        rating: 4.4,
        inStock: false,
    },
    {
        id: '7',
        name: 'Slipstream Future',
        brand: 'Puma',
        price: 134.99,
        image: '/images/sneaker-1.jpg',
        description:
            'Chunky profile reimagined with modern panels, padded collar, and durable outsole.',
        sizes: [6, 7, 8, 9, 10, 11, 12],
        colors: ['White', 'Black', 'Cyan'],
        rating: 4.3,
        inStock: true,
    },
    {
        id: '8',
        name: 'Chuck Next',
        brand: 'Converse',
        price: 89.99,
        image: '/images/sneaker-2.jpg',
        description:
            'Updated high-top classic with reinforced canvas, cushy insole, and bold contrast stitching.',
        sizes: [6, 7, 8, 9, 10, 11, 12, 13],
        colors: ['Black', 'White', 'Rust'],
        rating: 4.2,
        inStock: true,
    },
];
